### ISSUE TITLE
Demo Page: Dark theme is not applied correctly to the demo.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#294]
## Description:
In Chrome and Safari10 and FF57: Only the demo container and some of the components in properties container get the dark theme applied. Rest of the page remains in light theme.

In IE11: nothing seems to get themed properly except the view-header.

## Versions:
Browsers: Chrome63, FF57, Safari10 and IE11
Component/data-grid: Master

## Screenshot:
![dark-theme_demo](https://user-images.githubusercontent.com/10835611/34803006-aefcc61a-f625-11e7-823b-dde53fc103ed.png)

**Comment by randyaskin** [comment]
This is due to the fact that px-dark-demo-theme is not added in the theme-switcher. I actually fixed it in my local so that it will be added the first time you click the checkbox, but then couldn't figure out how to turn it back off again. :)

**Comment by alump** [comment]
@randyaskin what's the status with this, can we fix this now?

**Comment by randyaskin** [comment]
I thought all demo issues were on @davidrleonard 's plate

**Comment by ppeyro** [comment]
Agreed.  I think we decided to track them in this repo but David will take over any demo related issues once a handoff is completed.

**Comment by alump** [comment]
Ok, so nothing to do for us right now?

**Comment by Aileen-H** [comment]
PRIORITY 2

**Comment by ppeyro** [comment]
This is fixed after deployment to predix-ui.com. 
![screen shot 2018-03-05 at 9 24 59 am](https://user-images.githubusercontent.com/10835611/36989810-adb7f61a-2057-11e8-96ca-5fbbe77d2bdb.png)

 Closing this.
