### ISSUE TITLE
"Hide Column" needs to be optional

### ISSUE THREAD

**Issue by vonsichart200** [predixdesignsystem/px-data-grid#304]
Current:
"Hide column" is always enabled

Expected:
"Hide column" is optional

**Comment by alump** [comment]
This is new requirement, also it needs more information. Should there be master switch (so it will work with auto generated columns), or should there be hidable=false option in columns?

**Comment by Aileen-H** [comment]
1/16 - Agreed to add to enhancement list. Small enhancement but IE needs to be considered and may cause issues.

**Comment by Aileen-H** [comment]
PRIORITY 3
