### ISSUE TITLE
Datetime Picker cut off in editable table

### ISSUE THREAD

**Issue by randyaskin** [predixdesignsystem/px-data-grid#321]
When the table is space constrained and you enter edit mode, the datetime picker is cut off so you can't actually see what year you're entering:
![screen shot 2018-01-12 at 10 53 53 am](https://user-images.githubusercontent.com/2130613/34890506-0954dd7a-f787-11e7-9a9f-ce619e382923.png)

**Comment by Aileen-H** [comment]
1/16/18: Need to add minimum width. Enhancement.

**Comment by Aileen-H** [comment]
PRIORITY 2

**Comment by ppeyro** [comment]
@alump Retested this and it is still happening in V1.2.4.  
In the demo example specifically, it starts happening when width shrinks to about 650px.
![screen shot 2018-02-15 at 12 38 34 pm](https://user-images.githubusercontent.com/10835611/36279946-95d95060-124d-11e8-9a97-bc95a8ecfcb7.png)

It actually is worse in cases where there is a timestamp in the date column. The timestamp gets dropped all together when you go into the edit mode.

![screen shot 2018-02-15 at 12 44 09 pm](https://user-images.githubusercontent.com/10835611/36280103-1847aec0-124e-11e8-9b2a-938f10d8dc3a.png)

![screen shot 2018-02-15 at 12 44 23 pm](https://user-images.githubusercontent.com/10835611/36280111-1eb194ba-124e-11e8-8a23-546445f4a3f9.png)

## Code

https://gist.github.com/ppeyro/16ef9684b25038ff1a56eaa04a051ebe
