### ISSUE TITLE
Editable - save button should be grayed out

### ISSUE THREAD

**Issue by randyaskin** [predixdesignsystem/px-data-grid#325]
When a validation error occurs (due to required field, for example), the spec states that the save button should be grayed out. Especially useful if you've scrolled away from the invalid field and can only see the save/cancel buttons so you still have visual feedback of an error.
![screen shot 2018-01-12 at 11 34 01 am](https://user-images.githubusercontent.com/2130613/34892073-afb6eb04-f78c-11e7-9b88-217942b7a721.png)

**Comment by alump** [comment]
Not really, as validation can be what ever. Eg. application can expect time in the future, and after you have clicked the button, after next second same value might be valid. So as validation is totally custom thing, we can not assume same validation with same value will not pass on second try.

**Comment by Aileen-H** [comment]
1/16/18: Agreed this could be an enhancement. Need design for this.

**Comment by Aileen-H** [comment]
PRIORITY 3

**Comment by davidrleonard** [comment]
We're going to redesign the editing flow and solve this another way.
