### ISSUE TITLE
Custom Renderer and Resizable

### ISSUE THREAD

**Issue by randyaskin** [predixdesignsystem/px-data-grid#329]
This is a weird one... may just be an artifact of the demo page. If you go to the "Custom renderer demo" and move the icon column into the middle and resize it, it behaves different than a normal column. You can't adjust the size all the way down to zero, and the column to the right of it loses its padding.
![screen shot 2018-01-12 at 3 03 45 pm](https://user-images.githubusercontent.com/2130613/34898960-c61f33b0-f7aa-11e7-97e5-c807e545da69.png)

**Comment by alump** [comment]
So what is the actual issue here? Can be resized to 0? Is different how? Or what?

**Comment by Aileen-H** [comment]
1/16/2018: There should be minimum width for all the columns if you have resizable allowed. Agreed that this could be an enhancement

**Comment by Aileen-H** [comment]
PRIORITY 3

**Comment by drewharvey** [comment]
Task for this issue is to implement minimum width for columns.  This is essentially the same as #321.

**Comment by davidrleonard** [comment]
@randyaskin can you retest? :)
