### ISSUE TITLE
Expandable row should not change color when expanded

### ISSUE THREAD

**Issue by vonsichart200** [predixdesignsystem/px-data-grid#426]
**Current:**
Expanded row is colored $gray7 (Dark Theme: $gray19) and sometimes inherits the color of the (Zebra) Striping., which is unpredictable and creates visual inconsistency. 

**Expected:**
Suggestion to fix it with a low level of effort: Expandable row does not change color when expanded.

**Comment by Aileen-H** [comment]
PRIORITY 3
