### ISSUE TITLE
auto filter should support wildcard characters.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#461]
## Description
Currently auto filter doesn't support wildcard chars, like *, ?.
There is a reference to this in the design spec, so opening this issue for tracking, not sure if there was an agreement reached otherwise.

## Version
data-grid: V1.1.4

## Screenshot
###Spec
![screen shot 2018-01-23 at 3 50 49 pm](https://user-images.githubusercontent.com/10835611/35306950-48e621d4-0055-11e8-8c7a-e742dc066095.png)

###Example
![screen shot 2018-01-23 at 3 52 24 pm](https://user-images.githubusercontent.com/10835611/35307005-8db56a86-0055-11e8-91fa-7bb89cc1b226.png)

**Comment by alump** [comment]
Clear enhancement

**Comment by Aileen-H** [comment]
PRIORITY 2
