### ISSUE TITLE
Accessibility: Check keyboard navigation of Advanced Filtering dialog

### ISSUE THREAD

**Issue by alump** [predixdesignsystem/px-data-grid#475]
Check that user can fill the dialog with keyboard. Moving between dropdown and fields. And accessing add fields and reset/cancel/apply buttons.

Doesn't prevent first delivery.

**Comment by Toshegg** [comment]
@alump, should we navigate using arrow keys or just "Tab"?

**Comment by limonte** [comment]
> arrow keys or just "Tab"?

just Tab

**Comment by alump** [comment]
Tabs yes, arrow keys can and will be reserved go components. Also make sure the Xs and other buttons can be accessed with keyboard.

**Comment by Toshegg** [comment]
Depends on https://github.com/PredixDev/px-modal/issues/27

**Comment by davidrleonard** [comment]
I think this fix will need to be done outside px-modal, see my recent response on PredixDev/px-modal#27. We'll have to ensure our components that should be in the tabindex have the appropriate tab-index attribute and handle focus. Which components is this in relation to?

**Comment by Aileen-H** [comment]
PRIORITY 2

**Comment by andrealperry** [comment]
Needed for GA
