### ISSUE TITLE
Advanced Filtering: Implementation of filtering per Sections

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#535]
## Description

Design spec specifies an ability to setup filters based on predefined sections(Page 18 version 4 of the advanced filtering spec). This is not yet implemented as of V1.1.6 of data-grid.
Talked with Sami, he said not enough info was available to implement. 
Opening this ticket to track this.

## Version
Datagrid: V 1.1.6

## Screenshot
![screen shot 2018-01-29 at 9 09 19 am](https://user-images.githubusercontent.com/10835611/35523622-1c319f64-04d4-11e8-964e-843ff8fd5b35.png)

**Comment by alump** [comment]
This was excluded from this delivery for a reason. Marking as enhancement.

**Comment by Aileen-H** [comment]
PRIORITY 3

**Comment by andrealperry** [comment]
Nice to have
