### ISSUE TITLE
Advanced Filtering: Ability to customize headers in filter modal

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#537]
## Description 

Header labels in filter modal should be customizable per discussion with design team.
Currently, they're not customizable and are set to "Attribute, condition, value".

Was not able to find a specific statement in the design spec, but it came up during a discussion I had with the designers as a given requirement.

## Version
Data-grid: V1.1.6

## Screenshot
![screen shot 2018-01-29 at 9 19 55 am](https://user-images.githubusercontent.com/10835611/35525411-3b7d9e72-04d9-11e8-97ac-ef69d3b59fc1.png)

**Comment by alump** [comment]
New feature request, marking as enhancement.

**Comment by Aileen-H** [comment]
PRIORITY 3

**Comment by andrealperry** [comment]
Nice to have
