### ISSUE TITLE
Unfreeze all option should be implemented

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#539]
## Description

Unfreeze all option spec'd in the design is missing.
It is in the spec and I recall seeing it at some point and checked with Hans and he remembers seeing it as an item in Actions dropdown.  At any rate, it's no longer there, but present in the spec.

## Version
Data-grid: V1.1.6

## Screenshot
![screen shot 2018-01-29 at 3 29 11 pm](https://user-images.githubusercontent.com/10835611/35540195-a7e771ac-0509-11e8-923b-207bd2f2fc63.png)

**Comment by Aileen-H** [comment]
PRIORITY 3
