### ISSUE TITLE
Advanced Filtering: Selecting a filter chip should not clear the filter

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#543]
## Description
Per spec, selecting the "x" in the filter chip should remove the filter. The way it's implemented currently, the whole chip is selectable and will remove the filter on click.
This can be seen on the demo as well, so no test code provided.

## Version
Data-grid: V1.1.6
Browser: Safari10,Chrome

## Screenshot
![screen shot 2018-01-30 at 1 01 09 pm](https://user-images.githubusercontent.com/10835611/35591327-76d7b206-05be-11e8-9835-c37cb2b02f94.png)

**Comment by alump** [comment]
@toshegg can we have things inside chips with own click events and without breaking things?

**Comment by talimarcus** [comment]
I'm working on fixing this bug on our end and adding an enhancement to fire a separate event when the text in the chip is clicked (as opposed to the X icon)

**Comment by Aileen-H** [comment]
PRIORITY 2 (GE fixing px-chip)

**Comment by andrealperry** [comment]
Need for Beta

**Comment by davidrleonard** [comment]
This is waiting for a fix from @talimarcus in px-chip, which is still waiting on a branch.

**Comment by talimarcus** [comment]
Still waiting on https://github.com/webcomponents/shadydom/issues/190
