### ISSUE TITLE
Select all should only select the filtered rows

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#544]
## Description

If a filter is set and returns say 2 rows as the result doing a "select all"(checkbox), should only select the visible/filtered rows.  Currently, all rows in the grid will get selected not just the filtered rows.

## Version
Data-grid: V1.1.6

## Screenshot
![screen shot 2018-01-30 at 1 20 31 pm](https://user-images.githubusercontent.com/10835611/35591987-854758e4-05c0-11e8-91d7-b47b39f2e3d6.png)

**Comment by alump** [comment]
This might be considered as enhancement.

**Comment by alump** [comment]
Mainly because this get quite complicated if we change behavior to this. Specially the unselecting part.

**Comment by Aileen-H** [comment]
Are you saying to disable "Select all" when in "Filtering" mode?

**Comment by alump** [comment]
Disable select all and deselect action when content has been filtered. As it will get confusing and complex fast if it doesn't really anymore select and deselect all.

**Comment by Aileen-H** [comment]
Need a way to allow user to select all of the visible filtered results only to perform an action. 

PRIORITY 1

**Comment by alump** [comment]
Keeping this as enhancement. Only fix in scope of Q4 would be to prevent user adjusting selection when result set is different than all items.

**Comment by davidrleonard** [comment]
Estimating 2 weeks of development time (without testing) to implement.
