### ISSUE TITLE
Add/Delete row functionality: Implementation plan unclear

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#569]
## Description

**Add/delete row** functionality is currently not implemented, i.e. Selecting "add or delete row" in the dropdown, would not actually add or delete a row from the grid.  In the demo, selection of the option just triggers an event: "message displayed that the row was selected".

However, Add/delete row is specified in the design spec(Page 64&65), specifically noting API should be designed and implemented(see screenshot).  Based on what I understand, there are no plans by Vaadin team to implement this functionality.

Opening this issue to track this.

## Spec Screenshot

![screen shot 2018-02-01 at 11 55 36 am](https://user-images.githubusercontent.com/10835611/35700287-718496ea-0747-11e8-94c6-99cdd13161cc.png)

![screen shot 2018-02-01 at 11 53 21 am](https://user-images.githubusercontent.com/10835611/35700009-9843be06-0746-11e8-96dc-dc31fc1838ec.png)

**Comment by alump** [comment]
Works on our side, px-dropdown just still not fix.

**Comment by ppeyro** [comment]
This is not related to the dropdown. It's a tracking issue about the implementation of adding/deleting rows in the grid.
Could you please reopen this?

**Comment by alump** [comment]
Opening

**Comment by vonsichart200** [comment]
Which part of the specs are missing. Please elaborate.

**Comment by alump** [comment]
There is no definition what should happen when add row action is selected. For this reason the current version leaves that flow totally to application's responsibility.
