### ISSUE TITLE
Error message while in edit mode should be a tooltip.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#585]
## Description

Error messages that might happen during edits are spec'd as tooltips being triggered on error.  Doesn't seem to be the case.

## Version
Datagrid: V1.1.10

### Spec

![screen shot 2018-02-02 at 3 24 03 pm](https://user-images.githubusercontent.com/10835611/35759409-5c80439c-082e-11e8-8a37-ce394ba0306f.png)

### Implemented
<img width="942" alt="screen shot 2018-02-02 at 3 23 53 pm" src="https://user-images.githubusercontent.com/10835611/35759505-f90f2ad4-082e-11e8-9b03-c56c69106351.png">

## Code
https://gist.github.com/ppeyro/ed78396064a017c36badc164f26688b1

**Comment by alump** [comment]
This is chrome specific feature where it allows to write e to number field, but then causes native errors. Not sure if there is anything we can do here.

**Comment by ppeyro** [comment]
Thanks. I got the fact that "e" is the only allowable char in number cells in chrome which would trigger the native error msg.  I guess I know how to pick them :) 

Chrome is type checking the cell edits for the correct content type and won't allow the wrong type to be entered in the cell, but for example, Safari10 lets you enter the wrong type in the cell(screenshot below).
In this case when the user tries to save an edit should the error tooltip be triggered on hover when the cell is flagged as error'd (on save/cell highlighted in red)?   
I think this might be the case the design intended for this error tooltip. Giving users a hint what went wrong and why they can't save that edit.  Right now, the tooltip is not triggered in this case.

## Screenshots
### Safari10 can enter the wrong type
![screen shot 2018-02-06 at 12 26 13 pm](https://user-images.githubusercontent.com/10835611/35882520-595c24ac-0b39-11e8-99b1-ea909711a2aa.png)


### Chrome when trying to save an empty column
![screen shot 2018-02-06 at 12 01 08 pm](https://user-images.githubusercontent.com/10835611/35881734-a662af58-0b36-11e8-8bd4-9187227a0f5c.png)
