### ISSUE TITLE
Advanced Filtering: support for dropdown as a value

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#618]
## Description

The design spec shows the value field in the advanced filtering modal as having a dropdown. I believe the intention is to support more than just strings as "value" for filters.
There is no support for customizing the value field of the modal in the current version of the data-grid. 

Opening this tracking issue for future enhancements.

## Version
Data-grid: V1.1.11

## Screenshot
![screen shot 2018-02-07 at 3 48 15 pm](https://user-images.githubusercontent.com/10835611/35948605-323f6c82-0c22-11e8-9124-492763f13980.png)

**Comment by andrealperry** [comment]
Needed for GA
