### ISSUE TITLE
Advanced Filter: Date option in filter modal needs couple of visual fixes

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#630]
## Description

Couple of discrepancies between the spec and Filter modal:

1. Spec has timestamps included in the default view of range picker. Unsure if that should be just a visual fix with range picker's attributes showing a timestamp or fixing it would actually include implementing a "Time" column in the grid(in addition to number, string, date types).
WE WILL REMOVE THIS:
2. Header Text should be changed to match the spec: 
- Current: "FROM DATE" -> Should be: "FROM" 
-  Current: "TO DATE" -> Should be: "TO"

## Version
Data-grid: V1.1.11

### Timestamps in Spec vs. Code

![screen shot 2018-02-08 at 4 28 30 pm](https://user-images.githubusercontent.com/10835611/36006815-f7954278-0cf3-11e8-9a21-00bbbb3297e1.png)

### Header Text

![screen shot 2018-02-08 at 5 19 02 pm](https://user-images.githubusercontent.com/10835611/36006888-6581aec0-0cf4-11e8-9c69-1132226773b6.png)

**Comment by alump** [comment]
These are from px-rangepicker ... I assume, so these should be fixed there? @ppeyro

**Comment by ppeyro** [comment]
About the 2nd item in this issue:
You are right that it's range picker's header. I doubt we will change range picker to match the spec, so I already let the design team know the spec needs to be updated.

The first item is still pending. If you can please comment on that as well. Thanks.

**Comment by ppeyro** [comment]
Regarding the first item:
Since timestamps are not supported in the current implementation, for a visual fix you can set:
 "--px-datetime-range-field-margin-between-fields" to a larger value (default is 10) to fill the empty gap on the right hand side between the range picker and the X icon.

**Comment by alump** [comment]
Margin between fields doesn't resolve the issue, so I assume this has to be closed as wontfix, as neither of these issues will be resolved in px-rangepicker? @ppeyro

**Comment by ppeyro** [comment]
@alump  about the first item in this issue:
Doesn't "--px-datetime-range-field-margin-between-fields"  widen the gap between "from" field and "to" field?  Since "timestamps" is not a supported column type in the current version, the design workaround is to increase the gap between the "from" &  "to" fields so the big gap to the right of range picker is reduced.  This is a short term visual fix for the larger issue of unsupported timestamp column type.

I also checked with design regarding the 2nd issue"From Date", "To Date" and Andrea says the text discrepancy is fine for now since it's being passed from range picker.

**Comment by alump** [comment]
It makes the space bigger yes, but how about then when dialog gets smaller? Or when times are also shown? We can't fix this by setting absolute whitespace between fields, it should fill grow the empty space automatically to fix the issue.

**Comment by katemenkhaus** [comment]
I'll look into to options for making the spacing dynamic and get back to you.

**Comment by katemenkhaus** [comment]
In version `v2.1.5` of `px-datetime-range-field` I added the property `--px-datetime-range-field-justify-fields` which allows you to set `justify-content` on the fields. 
With the latest version `v3.3.4` of `px-rangepicker`, I add some css to get css var to work in rangepicker as well. 
Here is a glitch of the space between the fields being dynamic. 
https://glitch.com/edit/#!/excited-substance?path=public/app/px-rangepicker-scroll-demo.html:29:10

**Comment by alump** [comment]
I updated dependency, and defined variable: https://github.com/vaadin/px-data-grid/pull/681

**Comment by alump** [comment]
My bad, the correct value was ```space-between```, this is how it looks now, is this what you want:
<img width="870" alt="space-between" src="https://user-images.githubusercontent.com/1378660/36275673-59b22240-1240-11e8-9daf-22407f5d747d.png">

**Comment by alump** [comment]
This is how it looks if we later remove timezone from fields:
<img width="868" alt="without-timezones" src="https://user-images.githubusercontent.com/1378660/36275917-204026a0-1241-11e8-9b54-c9035c155442.png">

**Comment by katemenkhaus** [comment]
Ok let me give something a try.

**Comment by katemenkhaus** [comment]
We are going to solve the problem by use css-grid. This is going to take some time to test so I will let you know when it is released. css-grid is not supported in IE but will double check with the designers that that will be ok. 
![screen shot 2018-02-15 at 11 44 21 am](https://user-images.githubusercontent.com/14931112/36277360-816a0adc-1245-11e8-8afd-b6b532e30760.png)

**Comment by andrealperry** [comment]
Need for Beta

**Comment by drewharvey** [comment]
@katemenkhaus I set `full-width` (`fullWidth`) on the px-rangepicker, but now they are getting stacked.  It looks like each picker is taking 100% width.  I did not set anything to `--px-datetime-range-field-margin-between-fields`.

![full-width-issue](https://user-images.githubusercontent.com/2496955/36813020-e995fa34-1c87-11e8-8885-f0d7ae1b9f60.jpg)

**Comment by katemenkhaus** [comment]
I'm looking into. Thanks

**Comment by katemenkhaus** [comment]
The fields will stack by default when the container is smaller than 510px. I've documented how this works here https://www.predix-ui.com/#/elements/datetime/px-rangepicker:property-fullWidth

**Comment by katemenkhaus** [comment]
<img width="824" alt="screen shot 2018-02-28 at 12 57 28 pm" src="https://user-images.githubusercontent.com/14931112/36815956-44427742-1c91-11e8-96eb-defa570fd0bb.png">
Still looking into this issue

**Comment by drewharvey** [comment]
#713 fixes these issues from Vaadin's side.  I've been told by @katemenkhaus that leaving titles as "from date" and "to date" is OK (please correct me if I misunderstood).  

There is a problem in px-rangepicker which adds spacing below the component.  Once this is fixed we can close this issue.

**Comment by katemenkhaus** [comment]
Padding issue fixed in v3.4.2 of rangepicker

**Comment by drewharvey** [comment]
It looks better and the spacing issue is reduced, however, there is still extra spacing on the bottom.  The `px-dropdown` has no additional spacing on the bottom of the component.  I'm guessing the `px-rangepicker` should be the same?  Otherwise, we will need to vertically align these components, which could have annoying bugs in other browsers.  @katemenkhaus let me know what you think. 

<img width="824" alt="screen shot 2018-02-28 at 4 59 28 pm" src="https://user-images.githubusercontent.com/2496955/36821648-cd7bf972-1ca8-11e8-9518-e8ddfa873cd8.png">

**Comment by davidrleonard** [comment]
I asked @katemenkhaus to review this and weight in on whether its a problem on our end.

**Comment by katemenkhaus** [comment]
I'm sorry I didn't see you had replied. 
It looks like I messed up the versioning so you only got half of the fix. If you update to v3.5.1 of rangepicker all should be good.

**Comment by davidrleonard** [comment]
The first part of this issue is related to the timezone fix:

```
1. Spec has timestamps included in the default view of range picker. Unsure if that should be just a visual fix with range picker's attributes showing a timestamp or fixing it would actually include implementing a "Time" column in the grid(in addition to number, string, date types).
```

**Comment by ppeyro** [comment]
Rechecked in v1.0.0-beta.3. 
We now have an attribute `<filterByTime>` to turn on the timestamp in advanced filter for date columns.

The 2nd issue is not valid due to incorrect specs; since the header text is coming from the rangepicker and can't be modified. Design specs should be updated accordingly.


### Screenshot of advanced filter with timestamps
![screen shot 2018-03-14 at 10 19 18 am](https://user-images.githubusercontent.com/10835611/37419229-327f143a-2771-11e8-887e-5de5544bf8aa.png)
