### ISSUE TITLE
Advanced Filtering: Minor header alignment issue with Slider in Filter modal

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#631]
## Description

This is super minor: 
When Slider is used as the value, its header "RANGE" is placed slightly higher than header "ATTRIBUTE".

## Version
Data-grid: V1.1.11

## Screenshot
![screen shot 2018-02-08 at 5 27 10 pm](https://user-images.githubusercontent.com/10835611/36007133-d91c9a88-0cf5-11e8-814b-f7741ebd2eb0.png)

**Comment by alump** [comment]
@ppeyro Which one is correct? That slider header is from px-slider, not from us. We can only change our own headers. So if the left one is wrong it's our issue, if right one is wrong it's px-slider issue.

**Comment by ppeyro** [comment]
Ok. If it's slider and nothing can be done to fix the alignment in the modal, then I suppose we can close this off. Will let designers know this can't be fixed and won't match the spec.

**Comment by ppeyro** [comment]
Maybe I misunderstood your comment above.  We double checked the slider and the header is not coming from that component. Please recheck on your side.

**Comment by ppeyro** [comment]
Andrea created a visual for your reference:

![advancedfiltering_rangespec](https://user-images.githubusercontent.com/10835611/36043668-ec338b24-0d84-11e8-8b5e-fbf335936dc7.png)

**Comment by andrealperry** [comment]
Nice to have

**Comment by ppeyro** [comment]
Rechecked in v1.0.0-beta.3.  Misalignment is still happening. Latest screenshot below:

![screen shot 2018-03-14 at 10 11 23 am](https://user-images.githubusercontent.com/10835611/37418938-99e572aa-2770-11e8-85f2-37abfb10728c.png)
