### ISSUE TITLE
Paginated:  A partial separator line appears on horizontal scroll in multi-select grids

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#643]
## Description

This is a super edge case in multi select grids and more noticeable when you have 2 conditions:
1.  A horizontal scroll bar required to view additional columns on the right
2. A filter that returns an empty grid.

With these 2 conditions, note a vertical separator line appears in the first column of the header row when you scroll to the right to view additional columns.

## Version
Data-grid: V1.1.11 & Master

## Screenshot
![screen shot 2018-02-09 at 6 25 24 pm](https://user-images.githubusercontent.com/10835611/36057702-bc712904-0dc6-11e8-8423-330f78ccc2b5.png)

## Code
https://gist.github.com/ppeyro/e9c7e0784a0760c4342c2da412d6d94d

**Comment by alump** [comment]
In selection mode if no other columns are frozen the selection column is frozen, so it will get this line.
