### ISSUE TITLE
Advanced Filter:  Duration/Date range is not added as a filter chip on top of the grid

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#653]
## Description

When a date range/duration is used as a filter condition, it doesn't get listed in the list of filter chips on top of the grid.

## Version
Data-grid: V1.2.1
Browser: Chrome

## Screenshots
![screen shot 2018-02-12 at 5 31 27 pm](https://user-images.githubusercontent.com/10835611/36129211-dd55da1a-101a-11e8-92ee-3c4a95123b47.png)

![screen shot 2018-02-12 at 5 31 33 pm](https://user-images.githubusercontent.com/10835611/36129214-e05985cc-101a-11e8-89e1-f9ace0455dfa.png)

## Code
https://gist.github.com/ppeyro/b658bd7b991e2e6878580ba72c68af09

**Comment by andrealperry** [comment]
Please see the screenshot below of the updated spec (v6) that gives guidance for date ranges.

**px-tooltip** 
Option to display the full filter string in the tooltip component on hover. Note: show commas between the date and time and a dash to indicate ranges.

**px-chip - date time picker**
Show the date range with a dash (no spaces). Note: The date range example shown contains 21 characters and is an exception to the “truncate after 20 characters” rule.

![screen shot 2018-02-14 at 1 49 51 pm](https://user-images.githubusercontent.com/30873778/36230033-00c17bac-118e-11e8-8a15-29a6248a4109.png)

**Comment by andrealperry** [comment]
Needed for Beta

**Comment by drewharvey** [comment]
#710 fixes this except two minor pieces that cannot be done yet.

This can be closed once the following is done:
 - GE: px-tooltip fixes issue with the tooltip width: https://github.com/PredixDev/px-tooltip/issues/33
 - Vading: add timezone to end of tooltip message once timezone logic is implemented

**Comment by davidrleonard** [comment]
Retested and the chip is not showing up @drewharvey as of a31123514287a3f615021de5bd9d2ab73d5ec437

@andrealperry and @vonsichart200 will look to see if we can shorten the spec for what shows in the tooltip, if that's still an issue.

Need to retest after the timezone logic.

**Comment by ppeyro** [comment]
Verified this in v1.0.0-beta.3. We now get the filter chip for dateranges as well.
