### ISSUE TITLE
Advanced Filtering: artifact found after opening display rules dropdown (show/all)

### ISSUE THREAD

**Issue by andrealperry** [predixdesignsystem/px-data-grid#670]
After selecting the display rules dropdowns, a gray line artifact appears above the text.

![screen-shot-2018-02-14-at-2 06 04-pm](https://user-images.githubusercontent.com/30873778/36230926-fbb0908c-1190-11e8-9043-cdaedeba90ac.png)

**Comment by alump** [comment]
Can not reproduce, please define browser and version used.

**Comment by andrealperry** [comment]
Chrome Version 64.0.3282.140

**Comment by alump** [comment]
Can not reproduce with 1.2.4 and Chrome 64.0.3282.167 (Mac)

**Comment by andrealperry** [comment]
Updated to Version 64.0.3282.167 (Official Build) (64-bit) (Mac)

Still seeing the artifact:
![screen shot 2018-02-15 at 11 05 35 am](https://user-images.githubusercontent.com/30873778/36275639-3be958f0-1240-11e8-9974-a1c002a1adb6.png)

**Comment by limonte** [comment]
Chrome/Linux, Chrome/Windows - unable to reproduce with different page zoom values.

@andrealperry do you maybe have page zoom different from 100%?

**Comment by andrealperry** [comment]
@limonte page was set to 100%. @alump and @davidrleonard looked at the artifacts on screen last week and it the hypothesis is that it is a larger issue that is low priority.

**Comment by andrealperry** [comment]
Nice to have
