### ISSUE TITLE
Sorting a date column with invalid date causes unexpected ordering of results

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#704]
## Description

If you have a date column with invalid data row and you sort by selecting the header, the sort order looks unpredictable, invalid data row ends up in the middle of the sort order.

## Version
Data-grid: V1.2.4
Browser: Chrome

## Screenshot
![screen shot 2018-02-27 at 9 37 39 am](https://user-images.githubusercontent.com/10835611/36744821-a409e84e-1ba2-11e8-8b88-1d9928e0e71b.png)

## Code
https://gist.github.com/ppeyro/4631a0a51b7030c0bcc91bc8fa4d7159

**Comment by drewharvey** [comment]
Part of Q4 so this is no longer covered by the warranty.
