### ISSUE TITLE
IE11: Export to CSV in basic example demo doesn't work in IE11 only.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#719]
## Description

This is in the basic example demo.
In Actions dropdown, selecting export to CSV would export the grid content into a .csv file in all other browsers (that can be downloaded/viewed later).
Looks like the results of export is being dumped directly into a URL, causing IE11 to freak out.

## Version
Data-grid: V1.2.5
Browser: IE11

## Screenshot
![2018-03-01_1056](https://user-images.githubusercontent.com/10835611/36863719-65a03fec-1d3f-11e8-8408-89706c253f71.png)

**Comment by drewharvey** [comment]
Part of Q4 so this is no longer covered by the warranty.
