### ISSUE TITLE
Safari10: Filter contains gaps between fields in advanced filter modal.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#720]
## Description

Open the advanced filter modal for any of the simple demos in Safari10.
Add a filter; note the gaps between attribute/condition/value.

Other browsers (even IE11) look fine, see screenshot below.

## Version
Datagrid: V1.2.5
Browser: Safari10

## Screenshot
![screen shot 2018-03-01 at 11 06 49 am](https://user-images.githubusercontent.com/10835611/36864158-bd5e0484-1d40-11e8-9fd3-e3e81453422d.png)

**Comment by drewharvey** [comment]
Most likely a css issue with px-dropdown.
