### ISSUE TITLE
Advanced Filter: Rangepicker spacing is off in FF58 and misaligned in IE11

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#721]
# Description

### FF58:
When adding a filter for a date column, rangepicker's **from date**'s timezone is overlaid by the **To date**'s calendar icon. Same with **to date**'s timezone, it is partially overlaid on the delete **X**.

### IE11:
The rangepicker is rendered higher than the attribute.

## Version
Datagrid: V1.2.5
Browser: FF58 & IE11

## Screenshot
<img width="800" alt="screen shot 2018-03-01 at 11 46 25 am" src="https://user-images.githubusercontent.com/10835611/36866328-d3f0dc70-1d46-11e8-8a93-ebd09f998dfe.png">

**Comment by Aileen-H** [comment]
px-rangepicker issue @katemenkhaus

**Comment by katemenkhaus** [comment]
FF58 : The `--px-datetime-range-field-column-min-width` doesn't seem to be large enough. Firefox has a browser quirk where it doesn't resize the field to the correct size after the font as loaded. 

IE11: It seems to be adding about 10px padding at the bottom of the field. I'm not sure why still looking into it.
