### ISSUE TITLE
Filtering based on timestamps doesn't work

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#722]
## Description 

Create a grid with date columns that have the same date but different timestamps
Setup a filter to select a range with the same date but different timestamps, 11:00:00 to 17:00:00
Filtering returns an empty grid.
Expected to get the 2 rows with the same date/different timestamps.

## Version
Data-grid: V1.2.5
Browser: Chrome

## Screenshots
![screen shot 2018-03-01 at 12 04 37 pm](https://user-images.githubusercontent.com/10835611/36868308-d58a9bd8-1d4c-11e8-8fcf-331dd720d0a8.png)
![screen shot 2018-03-01 at 12 05 30 pm](https://user-images.githubusercontent.com/10835611/36868318-d92137b6-1d4c-11e8-9b9f-6da9ad824051.png)
![screen shot 2018-03-01 at 12 05 46 pm](https://user-images.githubusercontent.com/10835611/36868327-de489be4-1d4c-11e8-8e02-ad154e87c9d4.png)

## Code
https://gist.github.com/ppeyro/23984165aa7da1ebafa3495042a25872

**Comment by drewharvey** [comment]
@ppeyro can you retest?

**Comment by ppeyro** [comment]
Verified this in tag **v1.0.0-beta.3.**  Filtering based on timestamps looks good.

## Screenshot
![screen shot 2018-03-14 at 2 47 11 pm](https://user-images.githubusercontent.com/10835611/37432745-a95dcdb0-2796-11e8-8097-c93297c9b946.png)
