### ISSUE TITLE
Resizing columns' width should enforce a min/max.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#724]
## Description

When columns are set to resizable, adjusting the width doesn't enforce a minimum/max width on the neighboring column. Since a min width is not retained,  the column next to the resizable column can be completely overlaid by the column being resized.  Then the rows' height go crazy while of course Actions dropdown shows the overlaid column as still visible, even though it's not.

## Version
Datagrid: V1.2.5
Browser: Chrome, Safari10, FF58

## Screenshot
![screen shot 2018-03-01 at 12 55 16 pm](https://user-images.githubusercontent.com/10835611/36869223-daf3c786-1d4f-11e8-9801-b2837e596e3a.png)

**Comment by drewharvey** [comment]
Part of Q4 so this is no longer covered by the warranty.

**Comment by davidrleonard** [comment]
Designers will take a look and decide what to do.

Question:

* When the user drags a column to completely hide another, should it mark the invisible column as hidden now?
* Should columns have a min width when resizing so they can't be hidden completely?

cc @andrealperry @vonsichart200
