### ISSUE TITLE
Resizing the column while in edit mode causes a double scrollbar

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#727]
## Description

In paginated grid:
Go into edit mode, resize the column while in edit mode.
Notice the double horizontal scroll bars.
Doesn't happen in the demo probably because there are not enough columns to require the horizontal scroll ?

## Version
Datagrid: V1.2.5
Browser: Chrome

## Screenshot
![screen shot 2018-03-01 at 3 24 10 pm](https://user-images.githubusercontent.com/10835611/36875876-f9e87896-1d66-11e8-9bff-66b226f2de46.png)

## Code

https://gist.github.com/ppeyro/23984165aa7da1ebafa3495042a25872

**Comment by drewharvey** [comment]
Part of Q4 so this is no longer covered by the warranty.

**Comment by ppeyro** [comment]
Seen this in regular grid on chrome with  **v1.0.0-beta.4** as well.
Doesn't have to be in edit mode either. 

Load a wide grid with `grid-height=auto`, then resize a column before you scroll down the page. Once you scroll down you'll get the double horizontal scrollbars.

## Screenshot
![screen shot 2018-03-16 at 12 47 36 pm](https://user-images.githubusercontent.com/10835611/37541565-4ee37f0a-2918-11e8-9283-d0796aea0cda.png)
