### ISSUE TITLE
Error Tooltip can become detached if you scroll on the grid

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#728]
## Description

Trigger the error tooltip, for example, remove a number cell's content when required is set.
Now scroll in the grid, note the tooltip becomes detached from the cell that caused the error/highlighted in red.

## Version
Data-grid: V1.2.5

## Screenshot
![screen shot 2018-03-01 at 8 15 52 pm](https://user-images.githubusercontent.com/10835611/36883199-6128a4ce-1d8d-11e8-9e33-71de7080d19e.png)

**Comment by benoitjchevalier** [comment]
Actually a tooltip problem, we have the same issue when charts lock a tooltip in a scrollable container.

Not easy to solve, I think one of the google iron behavior deals with it now so using iron dropdown _might_ help... Anyway we should investigate that as part of tooltip

**Comment by davidrleonard** [comment]
Same problem in the charts, @benoitjchevalier will look into this.
