### ISSUE TITLE
Contextual Header menus don't seem to work in Safari

### ISSUE THREAD

**Issue by vonsichart200** [predixdesignsystem/px-data-grid#732]
**Expected:**
Clicking on the three dots next to the header labels opens a menu

**Current:** 
Clicking on the three dots has no result

Safari Version 11.0.3 (11604.5.6.1.1)

**Comment by ppeyro** [comment]
Looks like this is more than the contextual menu. Having problems with all dropdowns in Safari10, even in advanced filter. 

Additional Note: This is an issue on predix-ui **only.** All the dropdowns in the demo work fine in local env on safari10.

Also, don't think this is related, but getting this error in the console log when loading the demo in safari10:

![screen shot 2018-03-05 at 2 59 53 pm](https://user-images.githubusercontent.com/10835611/37004643-f0d72226-2085-11e8-85ee-66c1fef423bb.png)

**Comment by davidrleonard** [comment]
Confirmed this is broken in Safari 10 as well, but I have no clue why. It works in Chrome 64, Firefox 58.

Definitely related to #726 and #714.

I re-ran bower install locally and confirmed I was using the newest px-dropdown, v4.7.5, which is the same version that was installed on the predix-ui site in the latest build. I have no idea why it would be broken.

@mdwragg @randyaskin any thoughts?
