### ISSUE TITLE
IE11 acting up on the new paginated demo

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#737]
## Description

The new paginated demo works fine in other browsers but IE11 is being special again.

## Version
Data-grid branch: origin/paginated-demo
Browser: IE11

### Error when picking px-demo-paginated from the dropdown on top of page:

![2018-03-05_1700](https://user-images.githubusercontent.com/10835611/37008595-b7a9c7bc-2097-11e8-95d3-9c52ac2c719d.png)

### Sprinkled with more goodness errors:

![2018-03-05_1656](https://user-images.githubusercontent.com/10835611/37008627-e2dbbb84-2097-11e8-9c24-dfe9b7193a33.png)

### And the final result
![ie11_demo](https://user-images.githubusercontent.com/10835611/37008610-d12b65ba-2097-11e8-8e4a-683b9fb3de8e.png)

**Comment by davidrleonard** [comment]
Fixed in #761.
