### ISSUE TITLE
Demo/Property Editor: Focus is off in selectablepagesizes property/paginated demo

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#742]
## Description

In paginated demo, if you open the property editor for selectable page sizes, there is no way to place the cursor in the bracket.  You have to start typing outside of the bracket than back your way into the brackets using the left arrow key to add the page sizes you want to add.

## Version
paginated: origin/paginated-demo

## Screenshot
![screen shot 2018-03-06 at 11 56 02 am](https://user-images.githubusercontent.com/10835611/37055140-c7b04e94-2135-11e8-95b1-8110a91194c6.png)

**Comment by evanjd** [comment]
This appears to have been resolved elsewhere, I'm not able to reproduce this.
