### ISSUE TITLE
Demo/Property Editor/ paginated-grid: Property Editor doesn't work in Safari10

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#743]
## Description

Property Editor in paginated demo doesn't work in Safari10. Selecting an editor doesn't open it and there are no errors in the log either.  All other browsers are fine, even IE11.

## Version
Paginated: origin/paginated-demo

## Screenshot
![screen shot 2018-03-06 at 12 23 12 pm](https://user-images.githubusercontent.com/10835611/37056420-3e04d59e-2139-11e8-8982-c02a1e7d0401.png)

**Comment by evanbruhn-ge** [comment]
Appears to be resolved in Safari 11 as I'm not able to reproduce this. Closing for now.
