### ISSUE TITLE
Advanced filtering vs column filters

### ISSUE THREAD

**Issue by davidsteinberger** [predixdesignsystem/px-data-grid#750]
I like the way `px-data-grid`'s advanced filters allow users to construct more complex filters. I see the use-case for that, but miss the simplicity of `px-data-table`'s simple column filters. Those were less powerful and less flexible compared to the advanced filter, but quicker to use. Are there plans to support these too?

**Comment by skistz** [comment]
It's not prioritized at this time. That said, the auto filter input box searches across all the fields in the table.

**Comment by davidsteinberger** [comment]
The *auto-filter* while called a filter is more a search. It searches across *all* column and only filters out rows that have no match in any column. My concerns with the *auto-filter* are:

- From a user perspective I still think that the old column filters are quicker and more precise to use for simple use-cases.
- From a developer perspective, however, there's a big difference between the 2 (new auto-filter vs old column-filters) and the upgrade is going to be hard.  
We use `px-data-table` exclusively with the `dataRemote` option and do all filtering server-side. We use only public API for that e.g.: `px-filter-change-intent`. That API gives us the column-name and the filter criteria which we send to all our backend APIs.  
If *auto-filter* is indeed meant to be the replacement for that, you force everyone to change the backend API in order to support a search across the complete table-data.

Don't get me wrong, changes are good, the old `px-data-table` is one of the worst components in the *predixdesignsystem*. But we get into some uncomfortable situation here: there's no Polymer 2 suppport for `px-data-table` (in fact it's the only component which has not been made compatible) and IMO the new `px-data-grid` is not a drop-in-replacement.

**Comment by evanbruhn-ge** [comment]
@davidsteinberger We had similar thoughts and hope to add this some time in the future.

Closing for now as this thread has gone stale.
