### ISSUE TITLE
TimeZone: When editing a selected row, timezone text fades in the background color.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#757]
## Description

When editing a selected row, timezone text color fades into the selected row's background color _$select_default_ making the timezone invisible.

## Version
**Data-grid:** origin/feature/timezones
**Browsers:** Chrome, Safari10, FF58

## Screenshot
![screen shot 2018-03-12 at 4 40 09 pm](https://user-images.githubusercontent.com/10835611/37315030-a1a46ada-2614-11e8-94b6-8d49dc7b0b49.png)

**Comment by drewharvey** [comment]
Just set the timezone dropdown as a darker color.

**Comment by limonte** [comment]
I don't think this is the `px-data-grid` theming issue, but rather the a11y issue (low-contrast) of `px-datetime-entry`

**Comment by ppeyro** [comment]
Hans will re-evaluate the color scheme. Go Hans...
