### ISSUE TITLE
TimeZone: Layout in advanced filtering should be fixed up

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#763]
## Description

Looks like the timezone dropdown layout may need some tweaking.
See Screenshot below.

## Version
Datagrid: v1.0.0-beta.3
Browser: Chrome 64

## Screenshots
![screen shot 2018-03-13 at 6 35 37 pm](https://user-images.githubusercontent.com/10835611/37415938-dd049dec-2769-11e8-8964-2e60181fbf18.png)

![screen shot 2018-03-14 at 9 45 48 am](https://user-images.githubusercontent.com/10835611/37417054-8dbdefc4-276c-11e8-9cd5-8698529e0b63.png)

**Comment by katemenkhaus** [comment]
The second issue has been fixed. The `hoist` and `containerType` have been bound down to the timezone dropdown.

**Comment by evanbruhn-ge** [comment]
No longer reproducible, closing.
