### ISSUE TITLE
useTimeZones not working in advanced filtering

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#767]
## Description

In API doc:
`<useTimezones>`: _boolean = true_
_Set to true to be able to change timezones in the advanced filtering modal._

However in advanced filtering, timezone selection from the dropdown is always enabled regardless of `<useTimeZones>` set to false or true.

Should this be removed from the apidoc or should the functionality be implemented?

## Version
Datagrid:  v1.0.0-beta.3

**Comment by drewharvey** [comment]
This api will most likely change after we discuss the timezone api/design today.

**Comment by drewharvey** [comment]
Close this after merging #773.  It was agreed that we would remove this additional property and force the timezone to show as abbreviated and text (not editable).

**Comment by evanbruhn-ge** [comment]
Closing as #773 has been merged.
