### ISSUE TITLE
API Docs:  Update Columns section 

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#768]
## Description

Edit and update columns section of API docs:

- Move dateranges with the rest of date related options.
- Change dataFormat to dateformat.(Sort out dateFormat vs. dataFormat, dataFormat no longer valid after timezone changes)
- Add filterByTime, toggles visibility of timestamp in advanced filter.
- hideTime doesn't seem to have any effects ; filterByTime has to be set for timestamp to be removed from advanced filter. [Remove?]
- Remove ? from {?string} rendererConfig.displayFormat=null
- Remove "for the user" from displayFormat
- Update Code example to use dateFormat not dataFormat

**Comment by drewharvey** [comment]
Made changes to docs related to timezone changes.  Leaving this open because this seems like a place for notes.
