### ISSUE TITLE
Timezone: hidetime doesn't render the timestamp in edit mode

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#771]
## Description

Editing a cell doesn't render the timestamp even if `<hidetime>` is set to false and the `<datePickerTimeFormat>` is set to use a time format.

## Version
Datagrid: v1.0.0-beta.4

## Screenshot
![screen shot 2018-03-16 at 11 21 12 am](https://user-images.githubusercontent.com/10835611/37537919-48efee6e-290c-11e8-9132-33892fb136bb.png)

## Code
https://gist.github.com/ppeyro/501356268df6339ca380bccd144e0bdf

**Comment by drewharvey** [comment]
Possibly fixed by #775
