### ISSUE TITLE
Timezone: Filter chip's tooltip content not updated when timezone changes in advanced filter.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#774]
## Description

Changing timezones in the filter modal, doesn't seem to sync with the tooltip data in filter chip.

1. Displayformat & DateFormat defined with `timezone='Etc/GMT-7`
2. Data renders as expected in grid with timezone +07
3. In advanced Filter, selected `Etc/GMT-12` from the timezone dropdown and applied the filter.
4. Grid returns with no rows which is expected since the selected filter dates don't match any rows.
5. Hover over the chip filter to trigger the tooltip, notice tooltip content still shows +07 not +12 as the timezone criteria used for the filter.

## Version
Datagrid: v1.0.0-beta.4
Browser: Chrome

## Screenshot
![screen shot 2018-03-16 at 1 05 37 pm](https://user-images.githubusercontent.com/10835611/37542625-075d6322-291c-11e8-94cd-ba3cc9cc95eb.png)

**Comment by drewharvey** [comment]
This is not possible to reproduce anymore as users cannot change the timezone in the filtering dialog.  Closing.
