### ISSUE TITLE
Advanced Filter: need “Does not equal” condition

### ISSUE THREAD

**Issue by jimreedia** [predixdesignsystem/px-data-grid#780]
There are use cases when a user might need to use a “Does not equal” condition alongside another condition. See attached example. 
![screen shot 2018-03-20 at 2 47 58 pm](https://user-images.githubusercontent.com/8672799/37684659-fa503b7a-2c4d-11e8-955f-234ecb05ebf5.png)

**Comment by ppeyro** [comment]
That is actually configurable.  
You can use `number-comparators` to set your condition's dropdown options.

**Comment by evanbruhn-ge** [comment]
I'm interpreting this as a feature request. Currently, there is no `not_equal` comparator available for strings (not_equal is only available for numeric fields).

**Comment by evanjd** [comment]
@jimreedia I've added `not_equal` and `not_contains` string comparators to v1.2.0.
