### ISSUE TITLE
Incorrect(outdated?) documentation

### ISSUE THREAD

**Issue by vincentcn** [predixdesignsystem/px-data-grid#782]
I saw following sample renderer configuration sample for ```px-data-grid-date-renderer``` in https://www.predix-ui.com/#/elements/data-grid/px-data-grid.
```
{ 
   ...
    rendererConfig: {
    hideTime: true,
    displayFormat: 'YYYY/MM/DD',
    dataFormat: 'YYYY-MM-DD'
  },
  ...
}
```
Followed the format but it did not work. Checked source code of ```px-data-grid``` and found that correct configuration should be:
```
{
    "dateFormat": {
        "format": "YYYY-MM-DD",
        "timezone": "Asia/Shanghai"
    },
    "rendererConfig": {
        "displayFormat": "DD.MM.YYYY h:mm:ss a",
        "timezone": "Asia/Shanghai"
    }
}
```

Suppose the dateFormat config is mistaken to be "dataFormat" and nested into rendererConfig. Not sure whether the documentation is outdated. Maybe it is not a critical issue but really misleading.

**Comment by benoitjchevalier** [comment]
Yeah the doc is outdated, the format used to be different. Thanks for pointing this out
