### ISSUE TITLE
Chip render error after adv filtering

### ISSUE THREAD

**Issue by danharrelson** [predixdesignsystem/px-data-grid#791]
On the predix-ui.com site, after applying advanced filters, the "chip" is rendered with the close X misaligned and mis-sized.

![image](https://user-images.githubusercontent.com/91900/39153445-01fc4324-4700-11e8-84d1-6aa1ea110ff0.png)

**Comment by evanbruhn-ge** [comment]
This is an issue with [px-chip](https://github.com/predixdesignsystem/px-chip) and impacts all components that depend on it.

Related bug on px-chip: https://github.com/predixdesignsystem/px-chip

Will keep this bug open until the issue on px-chip is resolved.

**Comment by evanjd** [comment]
Fixed:
<img width="204" alt="screen shot 2018-08-07 at 3 52 21 pm" src="https://user-images.githubusercontent.com/4055224/43756862-f44785e2-9a59-11e8-9acd-80347e80f10d.png">
