### ISSUE TITLE
Any column option should not be hard-coded in the app for advance filter

### ISSUE THREAD

**Issue by sansantosh** [predixdesignsystem/px-data-grid#797]
For some use cases filtering by 'Any column' option is not required. There is no way to get rid of this option because it is hard coded in the code. 

          optionList.push({
            key: '-any-',
            val: 'Any column'
          });

**Comment by evanjd** [comment]
@sansantosh I've added the property `disable-all-columns-filter` to px-data-grid to allow the "Any column" filter to be suppressed. This is off by default.
