### ISSUE TITLE
how can we be notified of a change of value (ie : after a click on the save button) ?

### ISSUE THREAD

**Issue by stephanepilla** [predixdesignsystem/px-data-grid#809]
Hello,

I need to be notified of a value change after the user clicks on the save button in order to send the new value to the server.
How can this be done ?

I've already tried the following : 
- observer on the bound tableData property (changes are not notified to the parent)
- listener on the documented px-data-grid events (not fired in that case)
- listener on the "item-save" event (event fired but the modified row is not attached to the event detail and this event is anyway not documented in the public API)

Any other idea ?

**Comment by benoitjchevalier** [comment]
I guess the `item-save` would make the most sense, maybe issue a quick PR to add the saved item to this event? The item should be available in `e.model.item` in [here](https://github.com/predixdesignsystem/px-data-grid/blob/de6b3bdf6d83fb480bd3f214e66bb6bc841c9a40/px-data-grid-action-column.html#L189)

**Comment by stephanepilla** [comment]
Bonjour Benoit,

Thanks. I've just created the PR.

**Comment by benoitjchevalier** [comment]
Fixed in v1.0.8
